### ISSUE TITLE
"error : Incorrect string value: '\xF6X\xF6' for column 'denumire' at row 1" when trying to register XöXö as company name

### ISSUE THREAD

**Issue by sebiboga** [sebiboga/NIR#3]
please check collation for database / tables
we should allow all EU companies to be registered

**Comment by sebiboga** [comment]
I have added the accept-charset="utf-8" to the UI so the HTTP request NEEDS to send data to backend in UTF-8 charset encoding

**Comment by sebiboga** [comment]
marking this as RESOLVED / FIXED
@RoxanaDehelean please RETEST

**Comment by RoxanaDehelean** [comment]
Retested in QA environment
This issue has been fixed.
Closing the BUG
